// <auto-generated />
namespace AcunMedya.Restaurantly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig1productcategoryrelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1productcategoryrelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202501291809446_mig1productcategoryrelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
